-- ============================================================
-- 0022 — Six cities: Lahore, Karachi, Sialkot and Faisalabad join
-- Islamabad and Rawalpindi on Tuesday 6 October 2026 (00:00 PKT).
--
-- * cities.launch_at: a city with a future launch_at is open for sign-ups
--   and listings NOW (listings are saved), but its listings stay out of
--   public view until that moment — a pure date check in the read policy,
--   nothing to switch on. Owners and admins always see their own.
-- * Sialkot and Faisalabad added; Lahore and Karachi switched on.
-- * Area lists for all six cities (Zameen-style names; data/cities.json).
--   Existing areas are kept; only missing names are added.
-- Prices, payments, verification and every other rule are unchanged.
-- ============================================================

alter table public.cities add column if not exists launch_at timestamptz;

insert into public.cities (name, active, sort_order) values ('Sialkot', true, 5), ('Faisalabad', true, 6)
on conflict (name) do nothing;
update public.cities set active = true, launch_at = timestamptz '2026-10-06 00:00:00+05',
  sort_order = case name when 'Lahore' then 3 when 'Karachi' then 4 when 'Sialkot' then 5 else 6 end
where name in ('Lahore', 'Karachi', 'Sialkot', 'Faisalabad');

-- Is the city open to the public yet? (unknown / no date = yes)
create or replace function public.city_is_live(p_city text)
returns boolean language sql stable security definer set search_path = public
as $$ select not exists (select 1 from public.cities c where c.name = p_city and c.launch_at is not null and c.launch_at > now()) $$;
revoke execute on function public.city_is_live(text) from public;
grant execute on function public.city_is_live(text) to anon, authenticated, service_role;

-- Public read: active AND the city has launched. Owners/admins unchanged.
drop policy if exists "listings are publicly readable" on public.listings;
create policy "listings are publicly readable" on public.listings
  for select using ((moderation_status = 'active' and public.city_is_live(city)) or owner_id = auth.uid() or public.is_admin());

-- Areas (missing names only; existing rows and their order kept)
insert into public.areas (city_name, name, sort_order)
select v.city, v.name, coalesce((select max(a.sort_order) from public.areas a where a.city_name = v.city), 0) + v.ord
from (values
  ('Islamabad', 'Blue Area', 1),
  ('Islamabad', 'E-7', 2),
  ('Islamabad', 'E-11', 3),
  ('Islamabad', 'E-16', 4),
  ('Islamabad', 'E-17', 5),
  ('Islamabad', 'E-18', 6),
  ('Islamabad', 'F-5', 7),
  ('Islamabad', 'F-6', 8),
  ('Islamabad', 'F-7', 9),
  ('Islamabad', 'F-8', 10),
  ('Islamabad', 'F-9', 11),
  ('Islamabad', 'F-10', 12),
  ('Islamabad', 'F-11', 13),
  ('Islamabad', 'F-12', 14),
  ('Islamabad', 'F-15', 15),
  ('Islamabad', 'F-17', 16),
  ('Islamabad', 'G-5', 17),
  ('Islamabad', 'G-6', 18),
  ('Islamabad', 'G-7', 19),
  ('Islamabad', 'G-8', 20),
  ('Islamabad', 'G-9', 21),
  ('Islamabad', 'G-10', 22),
  ('Islamabad', 'G-11', 23),
  ('Islamabad', 'G-12', 24),
  ('Islamabad', 'G-13', 25),
  ('Islamabad', 'G-14', 26),
  ('Islamabad', 'G-15', 27),
  ('Islamabad', 'G-16', 28),
  ('Islamabad', 'H-13', 29),
  ('Islamabad', 'I-8', 30),
  ('Islamabad', 'I-9', 31),
  ('Islamabad', 'I-10', 32),
  ('Islamabad', 'I-11', 33),
  ('Islamabad', 'I-12', 34),
  ('Islamabad', 'I-14', 35),
  ('Islamabad', 'I-16', 36),
  ('Islamabad', 'D-12', 37),
  ('Islamabad', 'D-17', 38),
  ('Islamabad', 'B-17 Multi Gardens', 39),
  ('Islamabad', 'C-18', 40),
  ('Islamabad', 'Bani Gala', 41),
  ('Islamabad', 'Chak Shahzad', 42),
  ('Islamabad', 'Tarlai', 43),
  ('Islamabad', 'Bhara Kahu', 44),
  ('Islamabad', 'Shah Allah Ditta', 45),
  ('Islamabad', 'Golra Road', 46),
  ('Islamabad', 'Tarnol', 47),
  ('Islamabad', 'Lehtrar Road', 48),
  ('Islamabad', 'Park Road', 49),
  ('Islamabad', 'Kuri Road', 50),
  ('Islamabad', 'Islamabad Expressway', 51),
  ('Islamabad', 'Korang Town', 52),
  ('Islamabad', 'Pakistan Town', 53),
  ('Islamabad', 'PWD Housing Society', 54),
  ('Islamabad', 'Soan Garden', 55),
  ('Islamabad', 'Gulberg Greens', 56),
  ('Islamabad', 'Gulberg Residencia', 57),
  ('Islamabad', 'Bahria Enclave', 58),
  ('Islamabad', 'Naval Anchorage', 59),
  ('Islamabad', 'Airport Enclave', 60),
  ('Islamabad', 'Top City-1', 61),
  ('Islamabad', 'Park View City', 62),
  ('Islamabad', 'Faisal Hills', 63),
  ('Islamabad', 'CBR Town', 64),
  ('Islamabad', 'Margalla Town', 65),
  ('Islamabad', 'Zaraj Housing Scheme', 66),
  ('Islamabad', 'University Town', 67),
  ('Islamabad', 'Jinnah Garden', 68),
  ('Islamabad', 'Ghauri Town', 69),
  ('Islamabad', 'Mumtaz City', 70),
  ('Islamabad', 'Eighteen', 71),
  ('Islamabad', 'PECHS Islamabad', 72),
  ('Islamabad', 'Park Enclave', 73),
  ('Islamabad', 'Multi Residencia & Orchards', 74),
  ('Islamabad', 'Police Foundation', 75),
  ('Islamabad', 'National Police Foundation O-9', 76),
  ('Islamabad', 'Gulshan-e-Khudadad', 77),
  ('Islamabad', 'Federal Government Employees Housing', 78),
  ('Islamabad', 'Chatha Bakhtawar', 79),
  ('Islamabad', 'Alipur Farash', 80),
  ('Rawalpindi', 'Bahria Business District', 1),
  ('Rawalpindi', 'Bahria Paradise', 2),
  ('Rawalpindi', 'Bahria Town Phase 8 - Abu Bakar Block', 3),
  ('Rawalpindi', 'Bahria Town Phase 8 - Umer Block', 4),
  ('Rawalpindi', 'Bahria Town Phase 8 - Safari Valley', 5),
  ('Rawalpindi', 'Askari 1', 6),
  ('Rawalpindi', 'Askari 2', 7),
  ('Rawalpindi', 'Askari 7', 8),
  ('Rawalpindi', 'Askari 10', 9),
  ('Rawalpindi', 'Askari 11', 10),
  ('Rawalpindi', 'Askari 13', 11),
  ('Rawalpindi', 'Askari 14', 12),
  ('Rawalpindi', 'Satellite Town', 13),
  ('Rawalpindi', 'Satellite Town - Block A', 14),
  ('Rawalpindi', 'Satellite Town - Block B', 15),
  ('Rawalpindi', 'Chaklala Scheme 1', 16),
  ('Rawalpindi', 'Chaklala Scheme 2', 17),
  ('Rawalpindi', 'Chaklala Scheme 3', 18),
  ('Rawalpindi', 'Chaklala Scheme 4', 19),
  ('Rawalpindi', 'Westridge', 20),
  ('Rawalpindi', 'Gulraiz Housing Scheme', 21),
  ('Rawalpindi', 'Adiala Road', 22),
  ('Rawalpindi', 'Airport Housing Society', 23),
  ('Rawalpindi', 'Peshawar Road', 24),
  ('Rawalpindi', 'Murree Road', 25),
  ('Rawalpindi', 'Committee Chowk', 26),
  ('Rawalpindi', '6th Road', 27),
  ('Rawalpindi', '7th Road', 28),
  ('Rawalpindi', 'Sadiqabad', 29),
  ('Rawalpindi', 'Saddar', 30),
  ('Rawalpindi', 'Cantt', 31),
  ('Rawalpindi', 'Race Course Road', 32),
  ('Rawalpindi', 'Range Road', 33),
  ('Rawalpindi', 'Lalazar', 34),
  ('Rawalpindi', 'New Lalazar', 35),
  ('Rawalpindi', 'Gulzar-e-Quaid', 36),
  ('Rawalpindi', 'Naseerabad', 37),
  ('Rawalpindi', 'Dhoke Kashmirian', 38),
  ('Rawalpindi', 'Dhok Syedan Road', 39),
  ('Rawalpindi', 'Misrial Road', 40),
  ('Rawalpindi', 'Girja Road', 41),
  ('Rawalpindi', 'Defence Road', 42),
  ('Rawalpindi', 'Chakri Road', 43),
  ('Rawalpindi', 'GT Road', 44),
  ('Rawalpindi', 'Rawat', 45),
  ('Rawalpindi', 'Gulshan Abad', 46),
  ('Rawalpindi', 'Punjab Government Servants Housing Foundation', 47),
  ('Rawalpindi', 'Blue World City', 48),
  ('Rawalpindi', 'Media Town', 49),
  ('Rawalpindi', 'Gulistan Colony', 50),
  ('Rawalpindi', 'Harley Street', 51),
  ('Rawalpindi', 'Tench Bhatta', 52),
  ('Rawalpindi', 'Morgah', 53),
  ('Rawalpindi', 'Allama Iqbal Colony', 54),
  ('Rawalpindi', 'Shamsabad', 55),
  ('Rawalpindi', 'Muslim Town', 56),
  ('Rawalpindi', 'Khayaban-e-Sir Syed', 57),
  ('Rawalpindi', 'Dhamyal Road', 58),
  ('Rawalpindi', 'Car Chowk', 59),
  ('Rawalpindi', 'Kurri Road', 60),
  ('Rawalpindi', 'CBR Town Phase 2', 61),
  ('Rawalpindi', 'Islamabad Highway', 62),
  ('Lahore', 'DHA Lahore', 1),
  ('Lahore', 'DHA Phase 1 Lahore', 2),
  ('Lahore', 'DHA Phase 2 Lahore', 3),
  ('Lahore', 'DHA Phase 3 Lahore', 4),
  ('Lahore', 'DHA Phase 4 Lahore', 5),
  ('Lahore', 'DHA Phase 5 Lahore', 6),
  ('Lahore', 'DHA Phase 6 Lahore', 7),
  ('Lahore', 'DHA Phase 7 Lahore', 8),
  ('Lahore', 'DHA Phase 8 Lahore', 9),
  ('Lahore', 'DHA Phase 9 Prism', 10),
  ('Lahore', 'DHA Phase 9 Town', 11),
  ('Lahore', 'DHA Rahbar (Phase 11)', 12),
  ('Lahore', 'DHA Phase 13', 13),
  ('Lahore', 'Bahria Town Lahore', 14),
  ('Lahore', 'Bahria Orchard', 15),
  ('Lahore', 'Gulberg', 16),
  ('Lahore', 'Johar Town', 17),
  ('Lahore', 'Model Town', 18),
  ('Lahore', 'Garden Town', 19),
  ('Lahore', 'Faisal Town', 20),
  ('Lahore', 'Wapda Town', 21),
  ('Lahore', 'Allama Iqbal Town', 22),
  ('Lahore', 'Park View City Lahore', 23),
  ('Lahore', 'Raiwind Road', 24),
  ('Lahore', 'Central Park Housing Scheme', 25),
  ('Lahore', 'LDA Avenue', 26),
  ('Lahore', 'Lake City', 27),
  ('Lahore', 'Valencia Housing Society', 28),
  ('Lahore', 'Al Rehman Garden', 29),
  ('Lahore', 'Cantt Lahore', 30),
  ('Lahore', 'Askari Lahore', 31),
  ('Lahore', 'Cavalry Ground', 32),
  ('Lahore', 'Township', 33),
  ('Lahore', 'Green Town', 34),
  ('Lahore', 'Gulshan-e-Ravi', 35),
  ('Lahore', 'Samanabad', 36),
  ('Lahore', 'Shadman', 37),
  ('Lahore', 'Sabzazar', 38),
  ('Lahore', 'State Life Housing Society', 39),
  ('Lahore', 'Izmir Town', 40),
  ('Lahore', 'Canal Garden', 41),
  ('Lahore', 'Paragon City', 42),
  ('Lahore', 'Formanites Housing Scheme', 43),
  ('Lahore', 'Etihad Town', 44),
  ('Lahore', 'Al Kabir Town', 45),
  ('Lahore', 'Pak Arab Housing Society', 46),
  ('Lahore', 'Sui Gas Society', 47),
  ('Lahore', 'Punjab Cooperative Housing Society', 48),
  ('Lahore', 'NESPAK Housing Scheme', 49),
  ('Lahore', 'EME Society', 50),
  ('Lahore', 'Khayaban-e-Amin', 51),
  ('Lahore', 'Bankers Co-operative Housing Society', 52),
  ('Lahore', 'Lahore Motorway City', 53),
  ('Lahore', 'Thokar Niaz Baig', 54),
  ('Lahore', 'Multan Road', 55),
  ('Lahore', 'Ferozepur Road', 56),
  ('Lahore', 'Canal Road Lahore', 57),
  ('Lahore', 'Bedian Road', 58),
  ('Lahore', 'GT Road Lahore', 59),
  ('Lahore', 'Mall Road', 60),
  ('Lahore', 'Walton Road', 61),
  ('Lahore', 'Eden Lahore', 62),
  ('Lahore', 'Bahria Nasheman', 63),
  ('Lahore', 'New Lahore City', 64),
  ('Lahore', 'Lahore Smart City', 65),
  ('Karachi', 'DHA Karachi', 1),
  ('Karachi', 'DHA Phase 1 Karachi', 2),
  ('Karachi', 'DHA Phase 2 Karachi', 3),
  ('Karachi', 'DHA Phase 4 Karachi', 4),
  ('Karachi', 'DHA Phase 5 Karachi', 5),
  ('Karachi', 'DHA Phase 6 Karachi', 6),
  ('Karachi', 'DHA Phase 7 Karachi', 7),
  ('Karachi', 'DHA Phase 8 Karachi', 8),
  ('Karachi', 'DHA City Karachi', 9),
  ('Karachi', 'Clifton', 10),
  ('Karachi', 'Bath Island', 11),
  ('Karachi', 'Bahria Town Karachi', 12),
  ('Karachi', 'Gulshan-e-Iqbal', 13),
  ('Karachi', 'Scheme 33', 14),
  ('Karachi', 'Gulistan-e-Jauhar', 15),
  ('Karachi', 'North Nazimabad', 16),
  ('Karachi', 'Nazimabad', 17),
  ('Karachi', 'Naya Nazimabad', 18),
  ('Karachi', 'North Karachi', 19),
  ('Karachi', 'New Karachi', 20),
  ('Karachi', 'Federal B Area', 21),
  ('Karachi', 'PECHS', 22),
  ('Karachi', 'Tariq Road', 23),
  ('Karachi', 'Bahadurabad', 24),
  ('Karachi', 'Shahrah-e-Faisal', 25),
  ('Karachi', 'Karsaz', 26),
  ('Karachi', 'Navy Housing Scheme Karsaz', 27),
  ('Karachi', 'Askari 4 Karachi', 28),
  ('Karachi', 'Askari 5 Karachi', 29),
  ('Karachi', 'Cantt Karachi', 30),
  ('Karachi', 'Saddar Karachi', 31),
  ('Karachi', 'Malir', 32),
  ('Karachi', 'Malir Cantonment', 33),
  ('Karachi', 'Gadap Town', 34),
  ('Karachi', 'Korangi', 35),
  ('Karachi', 'Landhi', 36),
  ('Karachi', 'Shah Faisal Town', 37),
  ('Karachi', 'KDA Scheme 1', 38),
  ('Karachi', 'Gulshan-e-Maymar', 39),
  ('Karachi', 'Surjani Town', 40),
  ('Karachi', 'Scheme 45', 41),
  ('Karachi', 'Jamshed Town', 42),
  ('Karachi', 'Garden West', 43),
  ('Karachi', 'Model Colony', 44),
  ('Karachi', 'Mehmoodabad', 45),
  ('Karachi', 'Defence View', 46),
  ('Karachi', 'Buffer Zone', 47),
  ('Karachi', 'Gulshan-e-Hadeed', 48),
  ('Karachi', 'Falcon Complex Faisal', 49),
  ('Karachi', 'Orangi Town', 50),
  ('Karachi', 'Lyari', 51),
  ('Karachi', 'Kemari', 52),
  ('Karachi', 'Hawksbay', 53),
  ('Karachi', 'Jinnah Avenue', 54),
  ('Karachi', 'University Road', 55),
  ('Karachi', 'Super Highway', 56),
  ('Sialkot', 'Sialkot city', 1),
  ('Sialkot', 'Cantonment', 2),
  ('Sialkot', 'DHA Sialkot', 3),
  ('Sialkot', 'Citi Housing Sialkot', 4),
  ('Sialkot', 'Model Town Sialkot', 5),
  ('Sialkot', 'Ghalib Road', 6),
  ('Sialkot', 'Chenab Rangers Road', 7),
  ('Sialkot', 'Capital Road', 8),
  ('Sialkot', 'Wazirabad Road', 9),
  ('Sialkot', 'Daska Road', 10),
  ('Sialkot', 'Defence Road Sialkot', 11),
  ('Sialkot', 'Pasrur Road', 12),
  ('Sialkot', 'Kashmir Road', 13),
  ('Sialkot', 'Paris Road', 14),
  ('Sialkot', 'Shahab Pura Road', 15),
  ('Sialkot', 'Allama Iqbal Town Sialkot', 16),
  ('Sialkot', 'Sialkot Motorway', 17),
  ('Sialkot', 'Roras Road', 18),
  ('Sialkot', 'Khadim Ali Road', 19),
  ('Sialkot', 'Sambrial', 20),
  ('Sialkot', 'Ugoki', 21),
  ('Sialkot', 'Aimanabad Road', 22),
  ('Faisalabad', 'Faisalabad city', 1),
  ('Faisalabad', 'Citi Housing Faisalabad', 2),
  ('Faisalabad', 'Eden Valley', 3),
  ('Faisalabad', 'Eden Gardens', 4),
  ('Faisalabad', 'Eden Orchard', 5),
  ('Faisalabad', 'Canal Road Faisalabad', 6),
  ('Faisalabad', 'Wapda City', 7),
  ('Faisalabad', 'Satiana Road', 8),
  ('Faisalabad', 'Samundri Road', 9),
  ('Faisalabad', 'Lower Canal Road', 10),
  ('Faisalabad', 'Gulberg Valley', 11),
  ('Faisalabad', 'Madina Town', 12),
  ('Faisalabad', 'Peoples Colony', 13),
  ('Faisalabad', 'D Ground', 14),
  ('Faisalabad', 'Gulberg Faisalabad', 15),
  ('Faisalabad', 'Susan Road', 16),
  ('Faisalabad', 'Kohinoor City', 17),
  ('Faisalabad', 'Jaranwala Road', 18),
  ('Faisalabad', 'Sargodha Road', 19),
  ('Faisalabad', 'Jhang Road', 20),
  ('Faisalabad', 'Millat Road', 21),
  ('Faisalabad', 'Batala Colony', 22),
  ('Faisalabad', 'Gulistan Colony Faisalabad', 23),
  ('Faisalabad', 'Abdullah Garden', 24),
  ('Faisalabad', 'Officers Colony', 25),
  ('Faisalabad', 'Ghulam Muhammad Abad', 26),
  ('Faisalabad', 'Saeed Colony', 27),
  ('Faisalabad', 'Model City', 28),
  ('Faisalabad', 'Al Najaf Colony', 29),
  ('Faisalabad', 'Faisal Town Faisalabad', 30),
  ('Faisalabad', 'Raza Abad', 31),
  ('Islamabad', 'DHA Phase 1', 500),
  ('Rawalpindi', 'DHA Phase 1', 500),
  ('Islamabad', 'DHA Phase 2', 500),
  ('Rawalpindi', 'DHA Phase 2', 500),
  ('Islamabad', 'DHA Phase 3', 500),
  ('Rawalpindi', 'DHA Phase 3', 500),
  ('Islamabad', 'DHA Phase 4', 500),
  ('Rawalpindi', 'DHA Phase 4', 500),
  ('Islamabad', 'DHA Phase 5', 500),
  ('Rawalpindi', 'DHA Phase 5', 500),
  ('Rawalpindi', 'Bahria Town Phase 1', 500),
  ('Islamabad', 'Bahria Town Phase 1', 500),
  ('Rawalpindi', 'Bahria Town Phase 2', 500),
  ('Islamabad', 'Bahria Town Phase 2', 500),
  ('Rawalpindi', 'Bahria Town Phase 3', 500),
  ('Islamabad', 'Bahria Town Phase 3', 500),
  ('Rawalpindi', 'Bahria Town Phase 4', 500),
  ('Islamabad', 'Bahria Town Phase 4', 500),
  ('Rawalpindi', 'Bahria Town Phase 5', 500),
  ('Islamabad', 'Bahria Town Phase 5', 500),
  ('Rawalpindi', 'Bahria Town Phase 6', 500),
  ('Islamabad', 'Bahria Town Phase 6', 500),
  ('Rawalpindi', 'Bahria Town Phase 7', 500),
  ('Islamabad', 'Bahria Town Phase 7', 500),
  ('Rawalpindi', 'Bahria Town Phase 8', 500),
  ('Islamabad', 'Bahria Town Phase 8', 500),
  ('Rawalpindi', 'Capital Smart City', 500),
  ('Islamabad', 'Capital Smart City', 500),
  ('Islamabad', 'PWD Housing Society', 500),
  ('Rawalpindi', 'PWD Housing Society', 500)
) as v(city, name, ord)
where not exists (select 1 from public.areas a where a.city_name = v.city and lower(a.name) = lower(v.name));
